let stockProductos = [
    {id: 1, nombre: "Buzo negro", tipo: "buzo", cantidad: 1, desc: "Buzo para menores", precio: 1200, talle: "L", img: '../img/niño.jpg'},
    {id: 2, nombre: "Buzo Salmon", tipo: "buzo", cantidad: 1, desc: "Buzo para menores", precio: 1100, talle: "L", img: '../img/niño2.jpg'},
    {id: 3, nombre: "Campera negra", tipo: "campera", cantidad: 1, desc: "Campera para menores", precio: 1200, talle: "M", img: '../img/niño5.jpg'},
    {id: 4, nombre: "Campera amarilla", tipo: "campera", cantidad: 1, desc: "Campera para hombres", precio: 1400, talle: "M", img: '../img/campera5.jpeg'},
    {id: 5, nombre: "Campera roja", tipo: "campera", cantidad: 1, desc: "Campera para hombres", precio: 1200, talle: "S", img: '../img/campera7.jpeg'},
    {id: 6, nombre: "Gorra gris,azul", tipo: "gorra", cantidad: 1, desc: "Gorra de calabera negra", precio: 1500, img: '../img/gorra8.jpeg'},
    {id: 7, nombre: "Remera rosa", tipo: "remera", cantidad: 1, desc: "Remera para menores", precio: 500, talle: "L", img: '../img/niño4.jpg'},
    {id: 8, nombre: "Remera Negra", tipo: "remera", cantidad: 1, desc: "Remera para hombes", precio: 500, talle: "L", img: '../img/remerah11.jpeg'},
    {id: 9, nombre: "Remera Negra Tradicional", tipo: "remera", cantidad: 1, desc: "Remera para hombres", precio: 500, talle: "M", img: '../img/remerah12.jpeg'},
    {id: 10, nombre: "Gorra roja", tipo: "gorra", cantidad: 1, desc: "Gorra de RockIsDead", precio: 700, img: '../img/foto4.jpg'},
    {id: 11, nombre: "Gorra verde", tipo: "gorra", cantidad: 1,desc: "Gorra de RockIsDead", precio: 700, img: '../img/gorra7.jpeg'},
    {id: 12, nombre: "Campera Azul", tipo: "campera", cantidad: 1, desc: "Campera para mujeres", precio: 700, talle: "S", img: '../img/mujer.jpg'},
    {id: 13, nombre: "Campera Rosa", tipo: "campera", cantidad: 1, desc: "Campera para mujeres", precio: 900, talle: "L", img: '../img/mujer2.jpg'},
    {id: 14, nombre: "Remera Gris", tipo: "remera", cantidad: 1, desc: "Remera para mujeres", precio: 1400, talle: "S", img: '../img/mujer3.jpg'},
    {id: 15, nombre: "Buzo Negro", tipo: "buzo", cantidad: 1, desc: "Buzo para mujeres", precio: 7000, talle: "L", img: '../img/mujer4.jpg'},
    {id: 16, nombre: "Camisa a cuadros", tipo: "camisa", cantidad: 1, desc: "Camisa para mujeres", precio: 777, talle: "S", img: '../img/mujer5.jpg'},
    {id: 17, nombre: "Remera Gris", tipo: "remera", cantidad: 1, desc: "Remera para menores", precio: 1234, talle: "S", img: '../img/niño6.jpg'},
    {id: 18, nombre: "Pantalon Blanco", tipo: "pantalon", cantidad: 1, desc: "Pantalon para menores", precio: 155600, talle: "M", img: '../img/niño7.jpg'},
    {id: 19, nombre: "Pantalon vaquero", tipo: "pantalon", cantidad: 1, desc: "Pantalon vaquero para adultos", precio: 1600, talle: "L", img: '../img/pantalon1.jpg'},
    {id: 20, nombre: "Jean negro", tipo: "pantalon", cantidad: 1, desc: "Jean negro para adultos", precio: 3200, talle: "L", img: '../img/pantalon2.jpg'},
    {id: 21, nombre: "Jean negro", tipo: "pantalon", cantidad: 1, desc: "Pantalon para menores", precio: 2300, talle: "M", img: '../img/niño3.jpg'},
    {id: 22, nombre: "Campera Gris", tipo: "campera", cantidad: 1, desc: "Campera para menores", precio: 5600, talle: "M", img: '../img/niño8.jpg'},
    {id: 23, nombre: "Gorra Negra", tipo: "gorra", cantidad: 1, desc: "Gorra de Calabera Negra", precio: 1700, img: '../img/gorra9.jpeg'},
    {id: 24, nombre: "Gorra estilo militar", tipo: "gorra", cantidad: 1, desc: "Gorra de Calabera Negra", precio: 1800, img: '../img/gorra13.jpeg'},
]
